# Generated by Django 5.1.4 on 2024-12-30 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 6, 54, 4, 341390)),
        ),
    ]
