# Generated by Django 5.1.4 on 2024-12-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_Post',
        ),
    ]
