# Generated by Django 5.1.4 on 2024-12-30 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 7, 25, 40, 980374)),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='post_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
