# Generated by Django 5.1.4 on 2024-12-30 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_create_post_date_alter_create_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 7, 31, 24, 708574)),
        ),
    ]
