# Generated by Django 5.1.4 on 2024-12-31 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_create_post_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 6, 29, 49, 473806)),
        ),
    ]
