# Generated by Django 4.2.17 on 2025-01-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_create_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Create_Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
