# Generated by Django 4.2.17 on 2025-01-09 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_create_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 6, 3, 40, 964862)),
        ),
    ]
