# Generated by Django 4.2.17 on 2025-01-09 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_create_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='news_likes_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 8, 24, 43, 436622)),
        ),
    ]
