# Generated by Django 4.2.17 on 2025-01-13 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_create_post_news_likes_count_alter_create_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 6, 27, 46, 244961)),
        ),
    ]
