# Generated by Django 4.2.17 on 2025-01-21 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_create_post_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 10, 31, 40, 580342)),
        ),
    ]
